server:
  port: 8090
  servlet:
    context-path: "/upload"

spring:
  datasource:
    url: "jdbc:mysql://db:3306/file_db"
    username: root
    password: 1108
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
